// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/sensor/proto/sensor.proto

#ifndef PROTOBUF_cartographer_2fsensor_2fproto_2fsensor_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fsensor_2fproto_2fsensor_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/transform/proto/transform.pb.h"
// @@protoc_insertion_point(includes)
namespace cartographer {
namespace sensor {
namespace proto {
class CompressedPointCloud;
class CompressedPointCloudDefaultTypeInternal;
extern CompressedPointCloudDefaultTypeInternal _CompressedPointCloud_default_instance_;
class FixedFramePoseData;
class FixedFramePoseDataDefaultTypeInternal;
extern FixedFramePoseDataDefaultTypeInternal _FixedFramePoseData_default_instance_;
class ImuData;
class ImuDataDefaultTypeInternal;
extern ImuDataDefaultTypeInternal _ImuData_default_instance_;
class LandmarkData;
class LandmarkDataDefaultTypeInternal;
extern LandmarkDataDefaultTypeInternal _LandmarkData_default_instance_;
class LandmarkData_LandmarkObservation;
class LandmarkData_LandmarkObservationDefaultTypeInternal;
extern LandmarkData_LandmarkObservationDefaultTypeInternal _LandmarkData_LandmarkObservation_default_instance_;
class OdometryData;
class OdometryDataDefaultTypeInternal;
extern OdometryDataDefaultTypeInternal _OdometryData_default_instance_;
class RangeData;
class RangeDataDefaultTypeInternal;
extern RangeDataDefaultTypeInternal _RangeData_default_instance_;
class TimedPointCloudData;
class TimedPointCloudDataDefaultTypeInternal;
extern TimedPointCloudDataDefaultTypeInternal _TimedPointCloudData_default_instance_;
}  // namespace proto
}  // namespace sensor
}  // namespace cartographer

namespace cartographer {
namespace sensor {
namespace proto {

namespace protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto

// ===================================================================

class CompressedPointCloud : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.CompressedPointCloud) */ {
 public:
  CompressedPointCloud();
  virtual ~CompressedPointCloud();

  CompressedPointCloud(const CompressedPointCloud& from);

  inline CompressedPointCloud& operator=(const CompressedPointCloud& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CompressedPointCloud(CompressedPointCloud&& from) noexcept
    : CompressedPointCloud() {
    *this = ::std::move(from);
  }

  inline CompressedPointCloud& operator=(CompressedPointCloud&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CompressedPointCloud& default_instance();

  static inline const CompressedPointCloud* internal_default_instance() {
    return reinterpret_cast<const CompressedPointCloud*>(
               &_CompressedPointCloud_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CompressedPointCloud* other);
  friend void swap(CompressedPointCloud& a, CompressedPointCloud& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CompressedPointCloud* New() const PROTOBUF_FINAL { return New(NULL); }

  CompressedPointCloud* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CompressedPointCloud& from);
  void MergeFrom(const CompressedPointCloud& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CompressedPointCloud* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 point_data = 3;
  int point_data_size() const;
  void clear_point_data();
  static const int kPointDataFieldNumber = 3;
  ::google::protobuf::int32 point_data(int index) const;
  void set_point_data(int index, ::google::protobuf::int32 value);
  void add_point_data(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      point_data() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_point_data();

  // int32 num_points = 1;
  void clear_num_points();
  static const int kNumPointsFieldNumber = 1;
  ::google::protobuf::int32 num_points() const;
  void set_num_points(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.CompressedPointCloud)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > point_data_;
  mutable int _point_data_cached_byte_size_;
  ::google::protobuf::int32 num_points_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TimedPointCloudData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.TimedPointCloudData) */ {
 public:
  TimedPointCloudData();
  virtual ~TimedPointCloudData();

  TimedPointCloudData(const TimedPointCloudData& from);

  inline TimedPointCloudData& operator=(const TimedPointCloudData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TimedPointCloudData(TimedPointCloudData&& from) noexcept
    : TimedPointCloudData() {
    *this = ::std::move(from);
  }

  inline TimedPointCloudData& operator=(TimedPointCloudData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TimedPointCloudData& default_instance();

  static inline const TimedPointCloudData* internal_default_instance() {
    return reinterpret_cast<const TimedPointCloudData*>(
               &_TimedPointCloudData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(TimedPointCloudData* other);
  friend void swap(TimedPointCloudData& a, TimedPointCloudData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TimedPointCloudData* New() const PROTOBUF_FINAL { return New(NULL); }

  TimedPointCloudData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TimedPointCloudData& from);
  void MergeFrom(const TimedPointCloudData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TimedPointCloudData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cartographer.transform.proto.Vector4f point_data = 3;
  int point_data_size() const;
  void clear_point_data();
  static const int kPointDataFieldNumber = 3;
  const ::cartographer::transform::proto::Vector4f& point_data(int index) const;
  ::cartographer::transform::proto::Vector4f* mutable_point_data(int index);
  ::cartographer::transform::proto::Vector4f* add_point_data();
  ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector4f >*
      mutable_point_data();
  const ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector4f >&
      point_data() const;

  // .cartographer.transform.proto.Vector3f origin = 2;
  bool has_origin() const;
  void clear_origin();
  static const int kOriginFieldNumber = 2;
  const ::cartographer::transform::proto::Vector3f& origin() const;
  ::cartographer::transform::proto::Vector3f* mutable_origin();
  ::cartographer::transform::proto::Vector3f* release_origin();
  void set_allocated_origin(::cartographer::transform::proto::Vector3f* origin);

  // int64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.TimedPointCloudData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector4f > point_data_;
  ::cartographer::transform::proto::Vector3f* origin_;
  ::google::protobuf::int64 timestamp_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RangeData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.RangeData) */ {
 public:
  RangeData();
  virtual ~RangeData();

  RangeData(const RangeData& from);

  inline RangeData& operator=(const RangeData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RangeData(RangeData&& from) noexcept
    : RangeData() {
    *this = ::std::move(from);
  }

  inline RangeData& operator=(RangeData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RangeData& default_instance();

  static inline const RangeData* internal_default_instance() {
    return reinterpret_cast<const RangeData*>(
               &_RangeData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(RangeData* other);
  friend void swap(RangeData& a, RangeData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RangeData* New() const PROTOBUF_FINAL { return New(NULL); }

  RangeData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RangeData& from);
  void MergeFrom(const RangeData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RangeData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cartographer.transform.proto.Vector3f returns = 2;
  int returns_size() const;
  void clear_returns();
  static const int kReturnsFieldNumber = 2;
  const ::cartographer::transform::proto::Vector3f& returns(int index) const;
  ::cartographer::transform::proto::Vector3f* mutable_returns(int index);
  ::cartographer::transform::proto::Vector3f* add_returns();
  ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f >*
      mutable_returns();
  const ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f >&
      returns() const;

  // repeated .cartographer.transform.proto.Vector3f misses = 3;
  int misses_size() const;
  void clear_misses();
  static const int kMissesFieldNumber = 3;
  const ::cartographer::transform::proto::Vector3f& misses(int index) const;
  ::cartographer::transform::proto::Vector3f* mutable_misses(int index);
  ::cartographer::transform::proto::Vector3f* add_misses();
  ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f >*
      mutable_misses();
  const ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f >&
      misses() const;

  // .cartographer.transform.proto.Vector3f origin = 1;
  bool has_origin() const;
  void clear_origin();
  static const int kOriginFieldNumber = 1;
  const ::cartographer::transform::proto::Vector3f& origin() const;
  ::cartographer::transform::proto::Vector3f* mutable_origin();
  ::cartographer::transform::proto::Vector3f* release_origin();
  void set_allocated_origin(::cartographer::transform::proto::Vector3f* origin);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.RangeData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f > returns_;
  ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f > misses_;
  ::cartographer::transform::proto::Vector3f* origin_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ImuData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.ImuData) */ {
 public:
  ImuData();
  virtual ~ImuData();

  ImuData(const ImuData& from);

  inline ImuData& operator=(const ImuData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ImuData(ImuData&& from) noexcept
    : ImuData() {
    *this = ::std::move(from);
  }

  inline ImuData& operator=(ImuData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ImuData& default_instance();

  static inline const ImuData* internal_default_instance() {
    return reinterpret_cast<const ImuData*>(
               &_ImuData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ImuData* other);
  friend void swap(ImuData& a, ImuData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ImuData* New() const PROTOBUF_FINAL { return New(NULL); }

  ImuData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ImuData& from);
  void MergeFrom(const ImuData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ImuData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.transform.proto.Vector3d linear_acceleration = 2;
  bool has_linear_acceleration() const;
  void clear_linear_acceleration();
  static const int kLinearAccelerationFieldNumber = 2;
  const ::cartographer::transform::proto::Vector3d& linear_acceleration() const;
  ::cartographer::transform::proto::Vector3d* mutable_linear_acceleration();
  ::cartographer::transform::proto::Vector3d* release_linear_acceleration();
  void set_allocated_linear_acceleration(::cartographer::transform::proto::Vector3d* linear_acceleration);

  // .cartographer.transform.proto.Vector3d angular_velocity = 3;
  bool has_angular_velocity() const;
  void clear_angular_velocity();
  static const int kAngularVelocityFieldNumber = 3;
  const ::cartographer::transform::proto::Vector3d& angular_velocity() const;
  ::cartographer::transform::proto::Vector3d* mutable_angular_velocity();
  ::cartographer::transform::proto::Vector3d* release_angular_velocity();
  void set_allocated_angular_velocity(::cartographer::transform::proto::Vector3d* angular_velocity);

  // int64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.ImuData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Vector3d* linear_acceleration_;
  ::cartographer::transform::proto::Vector3d* angular_velocity_;
  ::google::protobuf::int64 timestamp_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OdometryData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.OdometryData) */ {
 public:
  OdometryData();
  virtual ~OdometryData();

  OdometryData(const OdometryData& from);

  inline OdometryData& operator=(const OdometryData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OdometryData(OdometryData&& from) noexcept
    : OdometryData() {
    *this = ::std::move(from);
  }

  inline OdometryData& operator=(OdometryData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const OdometryData& default_instance();

  static inline const OdometryData* internal_default_instance() {
    return reinterpret_cast<const OdometryData*>(
               &_OdometryData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(OdometryData* other);
  friend void swap(OdometryData& a, OdometryData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OdometryData* New() const PROTOBUF_FINAL { return New(NULL); }

  OdometryData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OdometryData& from);
  void MergeFrom(const OdometryData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OdometryData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.transform.proto.Rigid3d pose = 2;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 2;
  const ::cartographer::transform::proto::Rigid3d& pose() const;
  ::cartographer::transform::proto::Rigid3d* mutable_pose();
  ::cartographer::transform::proto::Rigid3d* release_pose();
  void set_allocated_pose(::cartographer::transform::proto::Rigid3d* pose);

  // int64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.OdometryData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Rigid3d* pose_;
  ::google::protobuf::int64 timestamp_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FixedFramePoseData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.FixedFramePoseData) */ {
 public:
  FixedFramePoseData();
  virtual ~FixedFramePoseData();

  FixedFramePoseData(const FixedFramePoseData& from);

  inline FixedFramePoseData& operator=(const FixedFramePoseData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FixedFramePoseData(FixedFramePoseData&& from) noexcept
    : FixedFramePoseData() {
    *this = ::std::move(from);
  }

  inline FixedFramePoseData& operator=(FixedFramePoseData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FixedFramePoseData& default_instance();

  static inline const FixedFramePoseData* internal_default_instance() {
    return reinterpret_cast<const FixedFramePoseData*>(
               &_FixedFramePoseData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(FixedFramePoseData* other);
  friend void swap(FixedFramePoseData& a, FixedFramePoseData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FixedFramePoseData* New() const PROTOBUF_FINAL { return New(NULL); }

  FixedFramePoseData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FixedFramePoseData& from);
  void MergeFrom(const FixedFramePoseData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FixedFramePoseData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.transform.proto.Rigid3d pose = 2;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 2;
  const ::cartographer::transform::proto::Rigid3d& pose() const;
  ::cartographer::transform::proto::Rigid3d* mutable_pose();
  ::cartographer::transform::proto::Rigid3d* release_pose();
  void set_allocated_pose(::cartographer::transform::proto::Rigid3d* pose);

  // int64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.FixedFramePoseData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Rigid3d* pose_;
  ::google::protobuf::int64 timestamp_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LandmarkData_LandmarkObservation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.LandmarkData.LandmarkObservation) */ {
 public:
  LandmarkData_LandmarkObservation();
  virtual ~LandmarkData_LandmarkObservation();

  LandmarkData_LandmarkObservation(const LandmarkData_LandmarkObservation& from);

  inline LandmarkData_LandmarkObservation& operator=(const LandmarkData_LandmarkObservation& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LandmarkData_LandmarkObservation(LandmarkData_LandmarkObservation&& from) noexcept
    : LandmarkData_LandmarkObservation() {
    *this = ::std::move(from);
  }

  inline LandmarkData_LandmarkObservation& operator=(LandmarkData_LandmarkObservation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LandmarkData_LandmarkObservation& default_instance();

  static inline const LandmarkData_LandmarkObservation* internal_default_instance() {
    return reinterpret_cast<const LandmarkData_LandmarkObservation*>(
               &_LandmarkData_LandmarkObservation_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(LandmarkData_LandmarkObservation* other);
  friend void swap(LandmarkData_LandmarkObservation& a, LandmarkData_LandmarkObservation& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LandmarkData_LandmarkObservation* New() const PROTOBUF_FINAL { return New(NULL); }

  LandmarkData_LandmarkObservation* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LandmarkData_LandmarkObservation& from);
  void MergeFrom(const LandmarkData_LandmarkObservation& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LandmarkData_LandmarkObservation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const void* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // .cartographer.transform.proto.Rigid3d landmark_to_tracking_transform = 2;
  bool has_landmark_to_tracking_transform() const;
  void clear_landmark_to_tracking_transform();
  static const int kLandmarkToTrackingTransformFieldNumber = 2;
  const ::cartographer::transform::proto::Rigid3d& landmark_to_tracking_transform() const;
  ::cartographer::transform::proto::Rigid3d* mutable_landmark_to_tracking_transform();
  ::cartographer::transform::proto::Rigid3d* release_landmark_to_tracking_transform();
  void set_allocated_landmark_to_tracking_transform(::cartographer::transform::proto::Rigid3d* landmark_to_tracking_transform);

  // double translation_weight = 3;
  void clear_translation_weight();
  static const int kTranslationWeightFieldNumber = 3;
  double translation_weight() const;
  void set_translation_weight(double value);

  // double rotation_weight = 4;
  void clear_rotation_weight();
  static const int kRotationWeightFieldNumber = 4;
  double rotation_weight() const;
  void set_rotation_weight(double value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.LandmarkData.LandmarkObservation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::cartographer::transform::proto::Rigid3d* landmark_to_tracking_transform_;
  double translation_weight_;
  double rotation_weight_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LandmarkData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.LandmarkData) */ {
 public:
  LandmarkData();
  virtual ~LandmarkData();

  LandmarkData(const LandmarkData& from);

  inline LandmarkData& operator=(const LandmarkData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LandmarkData(LandmarkData&& from) noexcept
    : LandmarkData() {
    *this = ::std::move(from);
  }

  inline LandmarkData& operator=(LandmarkData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LandmarkData& default_instance();

  static inline const LandmarkData* internal_default_instance() {
    return reinterpret_cast<const LandmarkData*>(
               &_LandmarkData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(LandmarkData* other);
  friend void swap(LandmarkData& a, LandmarkData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LandmarkData* New() const PROTOBUF_FINAL { return New(NULL); }

  LandmarkData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LandmarkData& from);
  void MergeFrom(const LandmarkData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LandmarkData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef LandmarkData_LandmarkObservation LandmarkObservation;

  // accessors -------------------------------------------------------

  // repeated .cartographer.sensor.proto.LandmarkData.LandmarkObservation landmark_observations = 2;
  int landmark_observations_size() const;
  void clear_landmark_observations();
  static const int kLandmarkObservationsFieldNumber = 2;
  const ::cartographer::sensor::proto::LandmarkData_LandmarkObservation& landmark_observations(int index) const;
  ::cartographer::sensor::proto::LandmarkData_LandmarkObservation* mutable_landmark_observations(int index);
  ::cartographer::sensor::proto::LandmarkData_LandmarkObservation* add_landmark_observations();
  ::google::protobuf::RepeatedPtrField< ::cartographer::sensor::proto::LandmarkData_LandmarkObservation >*
      mutable_landmark_observations();
  const ::google::protobuf::RepeatedPtrField< ::cartographer::sensor::proto::LandmarkData_LandmarkObservation >&
      landmark_observations() const;

  // int64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.LandmarkData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::cartographer::sensor::proto::LandmarkData_LandmarkObservation > landmark_observations_;
  ::google::protobuf::int64 timestamp_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CompressedPointCloud

// int32 num_points = 1;
inline void CompressedPointCloud::clear_num_points() {
  num_points_ = 0;
}
inline ::google::protobuf::int32 CompressedPointCloud::num_points() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.CompressedPointCloud.num_points)
  return num_points_;
}
inline void CompressedPointCloud::set_num_points(::google::protobuf::int32 value) {
  
  num_points_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.CompressedPointCloud.num_points)
}

// repeated int32 point_data = 3;
inline int CompressedPointCloud::point_data_size() const {
  return point_data_.size();
}
inline void CompressedPointCloud::clear_point_data() {
  point_data_.Clear();
}
inline ::google::protobuf::int32 CompressedPointCloud::point_data(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.CompressedPointCloud.point_data)
  return point_data_.Get(index);
}
inline void CompressedPointCloud::set_point_data(int index, ::google::protobuf::int32 value) {
  point_data_.Set(index, value);
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.CompressedPointCloud.point_data)
}
inline void CompressedPointCloud::add_point_data(::google::protobuf::int32 value) {
  point_data_.Add(value);
  // @@protoc_insertion_point(field_add:cartographer.sensor.proto.CompressedPointCloud.point_data)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CompressedPointCloud::point_data() const {
  // @@protoc_insertion_point(field_list:cartographer.sensor.proto.CompressedPointCloud.point_data)
  return point_data_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CompressedPointCloud::mutable_point_data() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.sensor.proto.CompressedPointCloud.point_data)
  return &point_data_;
}

// -------------------------------------------------------------------

// TimedPointCloudData

// int64 timestamp = 1;
inline void TimedPointCloudData::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 TimedPointCloudData::timestamp() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.TimedPointCloudData.timestamp)
  return timestamp_;
}
inline void TimedPointCloudData::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.TimedPointCloudData.timestamp)
}

// .cartographer.transform.proto.Vector3f origin = 2;
inline bool TimedPointCloudData::has_origin() const {
  return this != internal_default_instance() && origin_ != NULL;
}
inline void TimedPointCloudData::clear_origin() {
  if (GetArenaNoVirtual() == NULL && origin_ != NULL) delete origin_;
  origin_ = NULL;
}
inline const ::cartographer::transform::proto::Vector3f& TimedPointCloudData::origin() const {
  const ::cartographer::transform::proto::Vector3f* p = origin_;
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.TimedPointCloudData.origin)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector3f*>(
      &::cartographer::transform::proto::_Vector3f_default_instance_);
}
inline ::cartographer::transform::proto::Vector3f* TimedPointCloudData::mutable_origin() {
  
  if (origin_ == NULL) {
    origin_ = new ::cartographer::transform::proto::Vector3f;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.TimedPointCloudData.origin)
  return origin_;
}
inline ::cartographer::transform::proto::Vector3f* TimedPointCloudData::release_origin() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.TimedPointCloudData.origin)
  
  ::cartographer::transform::proto::Vector3f* temp = origin_;
  origin_ = NULL;
  return temp;
}
inline void TimedPointCloudData::set_allocated_origin(::cartographer::transform::proto::Vector3f* origin) {
  delete origin_;
  origin_ = origin;
  if (origin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.TimedPointCloudData.origin)
}

// repeated .cartographer.transform.proto.Vector4f point_data = 3;
inline int TimedPointCloudData::point_data_size() const {
  return point_data_.size();
}
inline void TimedPointCloudData::clear_point_data() {
  point_data_.Clear();
}
inline const ::cartographer::transform::proto::Vector4f& TimedPointCloudData::point_data(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.TimedPointCloudData.point_data)
  return point_data_.Get(index);
}
inline ::cartographer::transform::proto::Vector4f* TimedPointCloudData::mutable_point_data(int index) {
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.TimedPointCloudData.point_data)
  return point_data_.Mutable(index);
}
inline ::cartographer::transform::proto::Vector4f* TimedPointCloudData::add_point_data() {
  // @@protoc_insertion_point(field_add:cartographer.sensor.proto.TimedPointCloudData.point_data)
  return point_data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector4f >*
TimedPointCloudData::mutable_point_data() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.sensor.proto.TimedPointCloudData.point_data)
  return &point_data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector4f >&
TimedPointCloudData::point_data() const {
  // @@protoc_insertion_point(field_list:cartographer.sensor.proto.TimedPointCloudData.point_data)
  return point_data_;
}

// -------------------------------------------------------------------

// RangeData

// .cartographer.transform.proto.Vector3f origin = 1;
inline bool RangeData::has_origin() const {
  return this != internal_default_instance() && origin_ != NULL;
}
inline void RangeData::clear_origin() {
  if (GetArenaNoVirtual() == NULL && origin_ != NULL) delete origin_;
  origin_ = NULL;
}
inline const ::cartographer::transform::proto::Vector3f& RangeData::origin() const {
  const ::cartographer::transform::proto::Vector3f* p = origin_;
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.RangeData.origin)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector3f*>(
      &::cartographer::transform::proto::_Vector3f_default_instance_);
}
inline ::cartographer::transform::proto::Vector3f* RangeData::mutable_origin() {
  
  if (origin_ == NULL) {
    origin_ = new ::cartographer::transform::proto::Vector3f;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.RangeData.origin)
  return origin_;
}
inline ::cartographer::transform::proto::Vector3f* RangeData::release_origin() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.RangeData.origin)
  
  ::cartographer::transform::proto::Vector3f* temp = origin_;
  origin_ = NULL;
  return temp;
}
inline void RangeData::set_allocated_origin(::cartographer::transform::proto::Vector3f* origin) {
  delete origin_;
  origin_ = origin;
  if (origin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.RangeData.origin)
}

// repeated .cartographer.transform.proto.Vector3f returns = 2;
inline int RangeData::returns_size() const {
  return returns_.size();
}
inline void RangeData::clear_returns() {
  returns_.Clear();
}
inline const ::cartographer::transform::proto::Vector3f& RangeData::returns(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.RangeData.returns)
  return returns_.Get(index);
}
inline ::cartographer::transform::proto::Vector3f* RangeData::mutable_returns(int index) {
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.RangeData.returns)
  return returns_.Mutable(index);
}
inline ::cartographer::transform::proto::Vector3f* RangeData::add_returns() {
  // @@protoc_insertion_point(field_add:cartographer.sensor.proto.RangeData.returns)
  return returns_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f >*
RangeData::mutable_returns() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.sensor.proto.RangeData.returns)
  return &returns_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f >&
RangeData::returns() const {
  // @@protoc_insertion_point(field_list:cartographer.sensor.proto.RangeData.returns)
  return returns_;
}

// repeated .cartographer.transform.proto.Vector3f misses = 3;
inline int RangeData::misses_size() const {
  return misses_.size();
}
inline void RangeData::clear_misses() {
  misses_.Clear();
}
inline const ::cartographer::transform::proto::Vector3f& RangeData::misses(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.RangeData.misses)
  return misses_.Get(index);
}
inline ::cartographer::transform::proto::Vector3f* RangeData::mutable_misses(int index) {
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.RangeData.misses)
  return misses_.Mutable(index);
}
inline ::cartographer::transform::proto::Vector3f* RangeData::add_misses() {
  // @@protoc_insertion_point(field_add:cartographer.sensor.proto.RangeData.misses)
  return misses_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f >*
RangeData::mutable_misses() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.sensor.proto.RangeData.misses)
  return &misses_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cartographer::transform::proto::Vector3f >&
RangeData::misses() const {
  // @@protoc_insertion_point(field_list:cartographer.sensor.proto.RangeData.misses)
  return misses_;
}

// -------------------------------------------------------------------

// ImuData

// int64 timestamp = 1;
inline void ImuData::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ImuData::timestamp() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.ImuData.timestamp)
  return timestamp_;
}
inline void ImuData::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.ImuData.timestamp)
}

// .cartographer.transform.proto.Vector3d linear_acceleration = 2;
inline bool ImuData::has_linear_acceleration() const {
  return this != internal_default_instance() && linear_acceleration_ != NULL;
}
inline void ImuData::clear_linear_acceleration() {
  if (GetArenaNoVirtual() == NULL && linear_acceleration_ != NULL) delete linear_acceleration_;
  linear_acceleration_ = NULL;
}
inline const ::cartographer::transform::proto::Vector3d& ImuData::linear_acceleration() const {
  const ::cartographer::transform::proto::Vector3d* p = linear_acceleration_;
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.ImuData.linear_acceleration)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector3d*>(
      &::cartographer::transform::proto::_Vector3d_default_instance_);
}
inline ::cartographer::transform::proto::Vector3d* ImuData::mutable_linear_acceleration() {
  
  if (linear_acceleration_ == NULL) {
    linear_acceleration_ = new ::cartographer::transform::proto::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.ImuData.linear_acceleration)
  return linear_acceleration_;
}
inline ::cartographer::transform::proto::Vector3d* ImuData::release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.ImuData.linear_acceleration)
  
  ::cartographer::transform::proto::Vector3d* temp = linear_acceleration_;
  linear_acceleration_ = NULL;
  return temp;
}
inline void ImuData::set_allocated_linear_acceleration(::cartographer::transform::proto::Vector3d* linear_acceleration) {
  delete linear_acceleration_;
  linear_acceleration_ = linear_acceleration;
  if (linear_acceleration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.ImuData.linear_acceleration)
}

// .cartographer.transform.proto.Vector3d angular_velocity = 3;
inline bool ImuData::has_angular_velocity() const {
  return this != internal_default_instance() && angular_velocity_ != NULL;
}
inline void ImuData::clear_angular_velocity() {
  if (GetArenaNoVirtual() == NULL && angular_velocity_ != NULL) delete angular_velocity_;
  angular_velocity_ = NULL;
}
inline const ::cartographer::transform::proto::Vector3d& ImuData::angular_velocity() const {
  const ::cartographer::transform::proto::Vector3d* p = angular_velocity_;
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.ImuData.angular_velocity)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector3d*>(
      &::cartographer::transform::proto::_Vector3d_default_instance_);
}
inline ::cartographer::transform::proto::Vector3d* ImuData::mutable_angular_velocity() {
  
  if (angular_velocity_ == NULL) {
    angular_velocity_ = new ::cartographer::transform::proto::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.ImuData.angular_velocity)
  return angular_velocity_;
}
inline ::cartographer::transform::proto::Vector3d* ImuData::release_angular_velocity() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.ImuData.angular_velocity)
  
  ::cartographer::transform::proto::Vector3d* temp = angular_velocity_;
  angular_velocity_ = NULL;
  return temp;
}
inline void ImuData::set_allocated_angular_velocity(::cartographer::transform::proto::Vector3d* angular_velocity) {
  delete angular_velocity_;
  angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.ImuData.angular_velocity)
}

// -------------------------------------------------------------------

// OdometryData

// int64 timestamp = 1;
inline void OdometryData::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 OdometryData::timestamp() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.OdometryData.timestamp)
  return timestamp_;
}
inline void OdometryData::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.OdometryData.timestamp)
}

// .cartographer.transform.proto.Rigid3d pose = 2;
inline bool OdometryData::has_pose() const {
  return this != internal_default_instance() && pose_ != NULL;
}
inline void OdometryData::clear_pose() {
  if (GetArenaNoVirtual() == NULL && pose_ != NULL) delete pose_;
  pose_ = NULL;
}
inline const ::cartographer::transform::proto::Rigid3d& OdometryData::pose() const {
  const ::cartographer::transform::proto::Rigid3d* p = pose_;
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.OdometryData.pose)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Rigid3d*>(
      &::cartographer::transform::proto::_Rigid3d_default_instance_);
}
inline ::cartographer::transform::proto::Rigid3d* OdometryData::mutable_pose() {
  
  if (pose_ == NULL) {
    pose_ = new ::cartographer::transform::proto::Rigid3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.OdometryData.pose)
  return pose_;
}
inline ::cartographer::transform::proto::Rigid3d* OdometryData::release_pose() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.OdometryData.pose)
  
  ::cartographer::transform::proto::Rigid3d* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void OdometryData::set_allocated_pose(::cartographer::transform::proto::Rigid3d* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.OdometryData.pose)
}

// -------------------------------------------------------------------

// FixedFramePoseData

// int64 timestamp = 1;
inline void FixedFramePoseData::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 FixedFramePoseData::timestamp() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.FixedFramePoseData.timestamp)
  return timestamp_;
}
inline void FixedFramePoseData::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.FixedFramePoseData.timestamp)
}

// .cartographer.transform.proto.Rigid3d pose = 2;
inline bool FixedFramePoseData::has_pose() const {
  return this != internal_default_instance() && pose_ != NULL;
}
inline void FixedFramePoseData::clear_pose() {
  if (GetArenaNoVirtual() == NULL && pose_ != NULL) delete pose_;
  pose_ = NULL;
}
inline const ::cartographer::transform::proto::Rigid3d& FixedFramePoseData::pose() const {
  const ::cartographer::transform::proto::Rigid3d* p = pose_;
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.FixedFramePoseData.pose)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Rigid3d*>(
      &::cartographer::transform::proto::_Rigid3d_default_instance_);
}
inline ::cartographer::transform::proto::Rigid3d* FixedFramePoseData::mutable_pose() {
  
  if (pose_ == NULL) {
    pose_ = new ::cartographer::transform::proto::Rigid3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.FixedFramePoseData.pose)
  return pose_;
}
inline ::cartographer::transform::proto::Rigid3d* FixedFramePoseData::release_pose() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.FixedFramePoseData.pose)
  
  ::cartographer::transform::proto::Rigid3d* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void FixedFramePoseData::set_allocated_pose(::cartographer::transform::proto::Rigid3d* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.FixedFramePoseData.pose)
}

// -------------------------------------------------------------------

// LandmarkData_LandmarkObservation

// bytes id = 1;
inline void LandmarkData_LandmarkObservation::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LandmarkData_LandmarkObservation::id() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.LandmarkData.LandmarkObservation.id)
  return id_.GetNoArena();
}
inline void LandmarkData_LandmarkObservation::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.LandmarkData.LandmarkObservation.id)
}
#if LANG_CXX11
inline void LandmarkData_LandmarkObservation::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cartographer.sensor.proto.LandmarkData.LandmarkObservation.id)
}
#endif
inline void LandmarkData_LandmarkObservation::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cartographer.sensor.proto.LandmarkData.LandmarkObservation.id)
}
inline void LandmarkData_LandmarkObservation::set_id(const void* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cartographer.sensor.proto.LandmarkData.LandmarkObservation.id)
}
inline ::std::string* LandmarkData_LandmarkObservation::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.LandmarkData.LandmarkObservation.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LandmarkData_LandmarkObservation::release_id() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.LandmarkData.LandmarkObservation.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LandmarkData_LandmarkObservation::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.LandmarkData.LandmarkObservation.id)
}

// .cartographer.transform.proto.Rigid3d landmark_to_tracking_transform = 2;
inline bool LandmarkData_LandmarkObservation::has_landmark_to_tracking_transform() const {
  return this != internal_default_instance() && landmark_to_tracking_transform_ != NULL;
}
inline void LandmarkData_LandmarkObservation::clear_landmark_to_tracking_transform() {
  if (GetArenaNoVirtual() == NULL && landmark_to_tracking_transform_ != NULL) delete landmark_to_tracking_transform_;
  landmark_to_tracking_transform_ = NULL;
}
inline const ::cartographer::transform::proto::Rigid3d& LandmarkData_LandmarkObservation::landmark_to_tracking_transform() const {
  const ::cartographer::transform::proto::Rigid3d* p = landmark_to_tracking_transform_;
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.LandmarkData.LandmarkObservation.landmark_to_tracking_transform)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Rigid3d*>(
      &::cartographer::transform::proto::_Rigid3d_default_instance_);
}
inline ::cartographer::transform::proto::Rigid3d* LandmarkData_LandmarkObservation::mutable_landmark_to_tracking_transform() {
  
  if (landmark_to_tracking_transform_ == NULL) {
    landmark_to_tracking_transform_ = new ::cartographer::transform::proto::Rigid3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.LandmarkData.LandmarkObservation.landmark_to_tracking_transform)
  return landmark_to_tracking_transform_;
}
inline ::cartographer::transform::proto::Rigid3d* LandmarkData_LandmarkObservation::release_landmark_to_tracking_transform() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.LandmarkData.LandmarkObservation.landmark_to_tracking_transform)
  
  ::cartographer::transform::proto::Rigid3d* temp = landmark_to_tracking_transform_;
  landmark_to_tracking_transform_ = NULL;
  return temp;
}
inline void LandmarkData_LandmarkObservation::set_allocated_landmark_to_tracking_transform(::cartographer::transform::proto::Rigid3d* landmark_to_tracking_transform) {
  delete landmark_to_tracking_transform_;
  landmark_to_tracking_transform_ = landmark_to_tracking_transform;
  if (landmark_to_tracking_transform) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.LandmarkData.LandmarkObservation.landmark_to_tracking_transform)
}

// double translation_weight = 3;
inline void LandmarkData_LandmarkObservation::clear_translation_weight() {
  translation_weight_ = 0;
}
inline double LandmarkData_LandmarkObservation::translation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.LandmarkData.LandmarkObservation.translation_weight)
  return translation_weight_;
}
inline void LandmarkData_LandmarkObservation::set_translation_weight(double value) {
  
  translation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.LandmarkData.LandmarkObservation.translation_weight)
}

// double rotation_weight = 4;
inline void LandmarkData_LandmarkObservation::clear_rotation_weight() {
  rotation_weight_ = 0;
}
inline double LandmarkData_LandmarkObservation::rotation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.LandmarkData.LandmarkObservation.rotation_weight)
  return rotation_weight_;
}
inline void LandmarkData_LandmarkObservation::set_rotation_weight(double value) {
  
  rotation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.LandmarkData.LandmarkObservation.rotation_weight)
}

// -------------------------------------------------------------------

// LandmarkData

// int64 timestamp = 1;
inline void LandmarkData::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LandmarkData::timestamp() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.LandmarkData.timestamp)
  return timestamp_;
}
inline void LandmarkData::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.LandmarkData.timestamp)
}

// repeated .cartographer.sensor.proto.LandmarkData.LandmarkObservation landmark_observations = 2;
inline int LandmarkData::landmark_observations_size() const {
  return landmark_observations_.size();
}
inline void LandmarkData::clear_landmark_observations() {
  landmark_observations_.Clear();
}
inline const ::cartographer::sensor::proto::LandmarkData_LandmarkObservation& LandmarkData::landmark_observations(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.LandmarkData.landmark_observations)
  return landmark_observations_.Get(index);
}
inline ::cartographer::sensor::proto::LandmarkData_LandmarkObservation* LandmarkData::mutable_landmark_observations(int index) {
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.LandmarkData.landmark_observations)
  return landmark_observations_.Mutable(index);
}
inline ::cartographer::sensor::proto::LandmarkData_LandmarkObservation* LandmarkData::add_landmark_observations() {
  // @@protoc_insertion_point(field_add:cartographer.sensor.proto.LandmarkData.landmark_observations)
  return landmark_observations_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cartographer::sensor::proto::LandmarkData_LandmarkObservation >*
LandmarkData::mutable_landmark_observations() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.sensor.proto.LandmarkData.landmark_observations)
  return &landmark_observations_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cartographer::sensor::proto::LandmarkData_LandmarkObservation >&
LandmarkData::landmark_observations() const {
  // @@protoc_insertion_point(field_list:cartographer.sensor.proto.LandmarkData.landmark_observations)
  return landmark_observations_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace sensor
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fsensor_2fproto_2fsensor_2eproto__INCLUDED
