// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/range_data_inserter_options.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/mapping/proto/2d/probability_grid_range_data_inserter_options_2d.pb.h"
// @@protoc_insertion_point(includes)
namespace cartographer {
namespace mapping {
namespace proto {
class RangeDataInserterOptions;
class RangeDataInserterOptionsDefaultTypeInternal;
extern RangeDataInserterOptionsDefaultTypeInternal _RangeDataInserterOptions_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

namespace cartographer {
namespace mapping {
namespace proto {

namespace protobuf_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto

enum RangeDataInserterOptions_RangeDataInserterType {
  RangeDataInserterOptions_RangeDataInserterType_INVALID_INSERTER = 0,
  RangeDataInserterOptions_RangeDataInserterType_PROBABILITY_GRID_INSERTER_2D = 1,
  RangeDataInserterOptions_RangeDataInserterType_RangeDataInserterOptions_RangeDataInserterType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RangeDataInserterOptions_RangeDataInserterType_RangeDataInserterOptions_RangeDataInserterType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RangeDataInserterOptions_RangeDataInserterType_IsValid(int value);
const RangeDataInserterOptions_RangeDataInserterType RangeDataInserterOptions_RangeDataInserterType_RangeDataInserterType_MIN = RangeDataInserterOptions_RangeDataInserterType_INVALID_INSERTER;
const RangeDataInserterOptions_RangeDataInserterType RangeDataInserterOptions_RangeDataInserterType_RangeDataInserterType_MAX = RangeDataInserterOptions_RangeDataInserterType_PROBABILITY_GRID_INSERTER_2D;
const int RangeDataInserterOptions_RangeDataInserterType_RangeDataInserterType_ARRAYSIZE = RangeDataInserterOptions_RangeDataInserterType_RangeDataInserterType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RangeDataInserterOptions_RangeDataInserterType_descriptor();
inline const ::std::string& RangeDataInserterOptions_RangeDataInserterType_Name(RangeDataInserterOptions_RangeDataInserterType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RangeDataInserterOptions_RangeDataInserterType_descriptor(), value);
}
inline bool RangeDataInserterOptions_RangeDataInserterType_Parse(
    const ::std::string& name, RangeDataInserterOptions_RangeDataInserterType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RangeDataInserterOptions_RangeDataInserterType>(
    RangeDataInserterOptions_RangeDataInserterType_descriptor(), name, value);
}
// ===================================================================

class RangeDataInserterOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.RangeDataInserterOptions) */ {
 public:
  RangeDataInserterOptions();
  virtual ~RangeDataInserterOptions();

  RangeDataInserterOptions(const RangeDataInserterOptions& from);

  inline RangeDataInserterOptions& operator=(const RangeDataInserterOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RangeDataInserterOptions(RangeDataInserterOptions&& from) noexcept
    : RangeDataInserterOptions() {
    *this = ::std::move(from);
  }

  inline RangeDataInserterOptions& operator=(RangeDataInserterOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RangeDataInserterOptions& default_instance();

  static inline const RangeDataInserterOptions* internal_default_instance() {
    return reinterpret_cast<const RangeDataInserterOptions*>(
               &_RangeDataInserterOptions_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RangeDataInserterOptions* other);
  friend void swap(RangeDataInserterOptions& a, RangeDataInserterOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RangeDataInserterOptions* New() const PROTOBUF_FINAL { return New(NULL); }

  RangeDataInserterOptions* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RangeDataInserterOptions& from);
  void MergeFrom(const RangeDataInserterOptions& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RangeDataInserterOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef RangeDataInserterOptions_RangeDataInserterType RangeDataInserterType;
  static const RangeDataInserterType INVALID_INSERTER =
    RangeDataInserterOptions_RangeDataInserterType_INVALID_INSERTER;
  static const RangeDataInserterType PROBABILITY_GRID_INSERTER_2D =
    RangeDataInserterOptions_RangeDataInserterType_PROBABILITY_GRID_INSERTER_2D;
  static inline bool RangeDataInserterType_IsValid(int value) {
    return RangeDataInserterOptions_RangeDataInserterType_IsValid(value);
  }
  static const RangeDataInserterType RangeDataInserterType_MIN =
    RangeDataInserterOptions_RangeDataInserterType_RangeDataInserterType_MIN;
  static const RangeDataInserterType RangeDataInserterType_MAX =
    RangeDataInserterOptions_RangeDataInserterType_RangeDataInserterType_MAX;
  static const int RangeDataInserterType_ARRAYSIZE =
    RangeDataInserterOptions_RangeDataInserterType_RangeDataInserterType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RangeDataInserterType_descriptor() {
    return RangeDataInserterOptions_RangeDataInserterType_descriptor();
  }
  static inline const ::std::string& RangeDataInserterType_Name(RangeDataInserterType value) {
    return RangeDataInserterOptions_RangeDataInserterType_Name(value);
  }
  static inline bool RangeDataInserterType_Parse(const ::std::string& name,
      RangeDataInserterType* value) {
    return RangeDataInserterOptions_RangeDataInserterType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .cartographer.mapping.proto.ProbabilityGridRangeDataInserterOptions2D probability_grid_range_data_inserter_options_2d = 2;
  bool has_probability_grid_range_data_inserter_options_2d() const;
  void clear_probability_grid_range_data_inserter_options_2d();
  static const int kProbabilityGridRangeDataInserterOptions2DFieldNumber = 2;
  const ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D& probability_grid_range_data_inserter_options_2d() const;
  ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D* mutable_probability_grid_range_data_inserter_options_2d();
  ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D* release_probability_grid_range_data_inserter_options_2d();
  void set_allocated_probability_grid_range_data_inserter_options_2d(::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D* probability_grid_range_data_inserter_options_2d);

  // .cartographer.mapping.proto.RangeDataInserterOptions.RangeDataInserterType range_data_inserter_type = 1;
  void clear_range_data_inserter_type();
  static const int kRangeDataInserterTypeFieldNumber = 1;
  ::cartographer::mapping::proto::RangeDataInserterOptions_RangeDataInserterType range_data_inserter_type() const;
  void set_range_data_inserter_type(::cartographer::mapping::proto::RangeDataInserterOptions_RangeDataInserterType value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.RangeDataInserterOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D* probability_grid_range_data_inserter_options_2d_;
  int range_data_inserter_type_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RangeDataInserterOptions

// .cartographer.mapping.proto.RangeDataInserterOptions.RangeDataInserterType range_data_inserter_type = 1;
inline void RangeDataInserterOptions::clear_range_data_inserter_type() {
  range_data_inserter_type_ = 0;
}
inline ::cartographer::mapping::proto::RangeDataInserterOptions_RangeDataInserterType RangeDataInserterOptions::range_data_inserter_type() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.RangeDataInserterOptions.range_data_inserter_type)
  return static_cast< ::cartographer::mapping::proto::RangeDataInserterOptions_RangeDataInserterType >(range_data_inserter_type_);
}
inline void RangeDataInserterOptions::set_range_data_inserter_type(::cartographer::mapping::proto::RangeDataInserterOptions_RangeDataInserterType value) {
  
  range_data_inserter_type_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.RangeDataInserterOptions.range_data_inserter_type)
}

// .cartographer.mapping.proto.ProbabilityGridRangeDataInserterOptions2D probability_grid_range_data_inserter_options_2d = 2;
inline bool RangeDataInserterOptions::has_probability_grid_range_data_inserter_options_2d() const {
  return this != internal_default_instance() && probability_grid_range_data_inserter_options_2d_ != NULL;
}
inline void RangeDataInserterOptions::clear_probability_grid_range_data_inserter_options_2d() {
  if (GetArenaNoVirtual() == NULL && probability_grid_range_data_inserter_options_2d_ != NULL) delete probability_grid_range_data_inserter_options_2d_;
  probability_grid_range_data_inserter_options_2d_ = NULL;
}
inline const ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D& RangeDataInserterOptions::probability_grid_range_data_inserter_options_2d() const {
  const ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D* p = probability_grid_range_data_inserter_options_2d_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.RangeDataInserterOptions.probability_grid_range_data_inserter_options_2d)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D*>(
      &::cartographer::mapping::proto::_ProbabilityGridRangeDataInserterOptions2D_default_instance_);
}
inline ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D* RangeDataInserterOptions::mutable_probability_grid_range_data_inserter_options_2d() {
  
  if (probability_grid_range_data_inserter_options_2d_ == NULL) {
    probability_grid_range_data_inserter_options_2d_ = new ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.RangeDataInserterOptions.probability_grid_range_data_inserter_options_2d)
  return probability_grid_range_data_inserter_options_2d_;
}
inline ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D* RangeDataInserterOptions::release_probability_grid_range_data_inserter_options_2d() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.RangeDataInserterOptions.probability_grid_range_data_inserter_options_2d)
  
  ::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D* temp = probability_grid_range_data_inserter_options_2d_;
  probability_grid_range_data_inserter_options_2d_ = NULL;
  return temp;
}
inline void RangeDataInserterOptions::set_allocated_probability_grid_range_data_inserter_options_2d(::cartographer::mapping::proto::ProbabilityGridRangeDataInserterOptions2D* probability_grid_range_data_inserter_options_2d) {
  delete probability_grid_range_data_inserter_options_2d_;
  probability_grid_range_data_inserter_options_2d_ = probability_grid_range_data_inserter_options_2d;
  if (probability_grid_range_data_inserter_options_2d) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.RangeDataInserterOptions.probability_grid_range_data_inserter_options_2d)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::cartographer::mapping::proto::RangeDataInserterOptions_RangeDataInserterType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cartographer::mapping::proto::RangeDataInserterOptions_RangeDataInserterType>() {
  return ::cartographer::mapping::proto::RangeDataInserterOptions_RangeDataInserterType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto__INCLUDED
